### ISSUE TITLE
No option in the backend to chose the output (input or dropdown)

### ISSUE THREAD

**Issue by ThinkGraphical** [anomalylabs/country-field_type#5]
Looking at the code, i'm seeing checks wether to output a text input or dropdown.
But no option is shown in configuration when creating a new country-field.

**Comment by devillom** [comment]
in v3.1.1  no options

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/country-field_type/commit/b12acc4f6278fa3de72105b09424a37397d2073b

Please submit issues like this in the main pyrocms repository next time though so I don't lose them!

For example:

> [country-field_type] Your issue here
